# Generated by Django 4.0.5 on 2022-06-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='grydd_company',
        ),
    ]
