# Generated by Django 4.0.5 on 2022-06-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_company_email_alter_company_name_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='administered_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
