# Generated by Django 4.0.5 on 2022-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='name_shedule',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
