# Generated by Django 4.0.5 on 2022-06-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=130)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'grydd_status_access_point',
            },
        ),
        migrations.AlterField(
            model_name='accesspointcompany',
            name='geo_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesspointcompany',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_point.status'),
        ),
    ]
