# Generated by Django 4.0.5 on 2022-06-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
        ('access_point', '0002_status_alter_accesspointcompany_geo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointcompany',
            name='shedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.shedule'),
        ),
    ]
