# Generated by Django 4.0.5 on 2022-06-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_administered_user'),
        ('access_point', '0003_alter_accesspointcompany_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_point_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='accesspointcompany',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_point_company', to='access_point.status'),
        ),
    ]
